# Generated by Django 5.1.7 on 2025-06-18 11:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                ("seller_id", models.AutoField(primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "Seller",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=255, null=True)),
                ("last_name", models.CharField(max_length=255, null=True)),
                ("phone", models.CharField(max_length=20, null=True)),
                ("address", models.CharField(max_length=255, null=True)),
                ("role", models.CharField(max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "Users",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=255)),
                ("category_description", models.TextField(null=True)),
                ("category_isActive", models.BooleanField(default=True)),
                ("category_image", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.category",
                    ),
                ),
            ],
            options={
                "db_table": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=255)),
                ("product_price", models.IntegerField(default=0)),
                ("product_brief_description", models.CharField(max_length=255)),
                ("product_full_description", models.CharField(max_length=255)),
                (
                    "product_discountedPrice",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("product_sku", models.CharField(max_length=255)),
                ("product_unit", models.CharField(max_length=50, null=True)),
                (
                    "product_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("OUT_OF_STOCK", "Out of Stock"),
                            ("DISCONTINUED", "Discontinued"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("product_location", models.CharField(max_length=255, null=True)),
                ("quantity", models.IntegerField(default=0)),
                ("post_date", models.DateTimeField(null=True)),
                ("harvest_date", models.DateTimeField(null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "discounted_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("is_discounted", models.BooleanField(default=False)),
                ("is_sale", models.BooleanField(default=False)),
                ("is_srp", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("top_rated", models.BooleanField(default=False)),
                ("sell_count", models.IntegerField(default=0)),
                ("offer_start_date", models.DateTimeField(null=True)),
                ("offer_end_date", models.DateTimeField(null=True)),
                (
                    "promo_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.category"
                    ),
                ),
            ],
            options={
                "db_table": "Products",
            },
        ),
        migrations.CreateModel(
            name="ProductSeller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.product"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.seller"
                    ),
                ),
            ],
            options={
                "db_table": "ProductSeller",
                "unique_together": {("seller", "product")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="sellers",
            field=models.ManyToManyField(through="api.ProductSeller", to="api.seller"),
        ),
        migrations.AddField(
            model_name="seller",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
        ),
    ]
