# Generated by Django 5.1.7 on 2025-06-18 13:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AlterUniqueTogether(
            name="productseller",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="productseller",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productseller",
            name="seller",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sellers",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="user",
        ),
        migrations.RemoveField(
            model_name="product",
            name="user",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_unit",
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="post_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="ProductSeller",
        ),
        migrations.DeleteModel(
            name="Seller",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
