# Generated by Django 5.1.7 on 2025-07-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_user_user_address_user_barangay_user_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seller",
            name="business_address",
        ),
        migrations.AddField(
            model_name="seller",
            name="barangay",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="province",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="street",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
