# Generated by Django 5.1.7 on 2025-06-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_category_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="category",
            new_name="category_id",
        ),
    ]
