# Generated by Django 5.1.7 on 2025-07-22 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_seller_business_address_seller_barangay_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subcategory",
            options={"verbose_name": "SubCategory"},
        ),
        migrations.AlterModelTable(
            name="payment",
            table="Payments",
        ),
    ]
