# Generated by Django 5.1.7 on 2025-06-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_category_product_category_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="category_description",
        ),
        migrations.RemoveField(
            model_name="category",
            name="parent_category",
        ),
    ]
