# Generated by Django 5.1.7 on 2025-07-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_subcategory_options_alter_payment_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="payment_date",
        ),
        migrations.AddField(
            model_name="payment",
            name="revenue",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
