# Generated by Django 5.1.7 on 2025-06-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_category_category_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_sale",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_srp",
        ),
        migrations.AlterField(
            model_name="category",
            name="category_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="category_images/"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
