# Generated by Django 5.1.7 on 2025-07-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_seller_is_verified_seller_terms_accepted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_email",
            field=models.EmailField(default="", max_length=254, unique=True),
        ),
    ]
