# Generated by Django 5.1.7 on 2025-06-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_product_is_sale_remove_product_is_srp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_sale",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_srp",
            field=models.BooleanField(default=False),
        ),
    ]
