# Generated by Django 5.1.7 on 2025-07-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_user_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="seller_first_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="seller",
            name="seller_last_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
