# Generated by Django 5.1.7 on 2025-06-19 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_product_is_sale_product_is_srp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_sale",
        ),
    ]
