# Generated by Django 5.1.7 on 2025-06-19 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_product_is_sale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="discounted_amount",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_discounted",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_srp",
        ),
    ]
