# Generated by Django 5.1.7 on 2025-07-25 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_seller_seller_first_name_seller_seller_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seller",
            name="seller_first_name",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="seller_last_name",
        ),
    ]
