# Generated by Django 5.1.7 on 2025-07-16 04:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_product_approval_status_user_approval_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="approval_status",
        ),
        migrations.RemoveField(
            model_name="user",
            name="approval_status",
        ),
        migrations.AlterField(
            model_name="product",
            name="product_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="review_rating",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.DeleteModel(
            name="ApprovalStatus",
        ),
    ]
