# Generated by Django 5.1.7 on 2025-06-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_product_discounted_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_discounted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_srp",
            field=models.BooleanField(default=False),
        ),
    ]
