# Generated by Django 5.1.7 on 2025-07-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_seller_seller_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="gateway_response",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
