# Generated by Django 5.1.7 on 2025-07-15 07:14

from django.db import migrations
from django.contrib.auth.models import Group


def assign_users_to_groups(apps, schema_editor):
    """Assign existing users to appropriate groups based on their role field"""
    User = apps.get_model('api', 'User')
    
    # Get or create groups (they should already exist from setup_groups command)
    admin_group, _ = Group.objects.get_or_create(name='Admin')
    seller_group, _ = Group.objects.get_or_create(name='Seller')
    customer_group, _ = Group.objects.get_or_create(name='Customer')
    
    # Statistics tracking
    assigned_counts = {'admin': 0, 'seller': 0, 'customer': 0, 'unknown': 0}
    
    # Assign existing users to appropriate groups
    for user in User.objects.all():
        if user.role == 'admin':
            user.groups.add(admin_group)
            assigned_counts['admin'] += 1
        elif user.role == 'seller':
            user.groups.add(seller_group)
            assigned_counts['seller'] += 1
        elif user.role == 'customer':
            user.groups.add(customer_group)
            assigned_counts['customer'] += 1
        else:
            # Default unknown roles to customer
            user.groups.add(customer_group)
            assigned_counts['unknown'] += 1
    
    print(f"\nUser group assignment completed:")
    print(f"  - {assigned_counts['admin']} users assigned to Admin group")
    print(f"  - {assigned_counts['seller']} users assigned to Seller group")
    print(f"  - {assigned_counts['customer']} users assigned to Customer group")
    print(f"  - {assigned_counts['unknown']} users with unknown roles assigned to Customer group")


def reverse_assign_users_to_groups(apps, schema_editor):
    """Remove all group assignments (for rollback)"""
    User = apps.get_model('api', 'User')
    
    # Clear all group assignments
    for user in User.objects.all():
        user.groups.clear()
    
    print("All user group assignments have been cleared")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_product_approval_status_user_approval_status_and_more"),
    ]

    operations = [
        migrations.RunPython(
            assign_users_to_groups,
            reverse_assign_users_to_groups
        ),
    ]
