# Generated by Django 5.1.7 on 2025-06-19 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_remove_product_promo_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("user_email", models.EmailField(max_length=254, unique=True)),
                ("user_password", models.CharField(max_length=255)),
                ("user_phone", models.CharField(max_length=255)),
                ("user_address", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="user_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
        ),
    ]
