# Generated by Django 5.1.7 on 2025-07-16 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="id",
            new_name="cart_id",
        ),
        migrations.RenameField(
            model_name="cartitem",
            old_name="id",
            new_name="cart_item_id",
        ),
    ]
