# Generated by Django 5.1.7 on 2025-06-19 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_user_product_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                ("seller_id", models.AutoField(primary_key=True, serialize=False)),
                ("business_name", models.CharField(max_length=255)),
                ("business_email", models.EmailField(max_length=254, unique=True)),
                ("business_phone", models.CharField(max_length=255)),
                ("business_address", models.CharField(max_length=255, null=True)),
                (
                    "total_earnings",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                ("total_products", models.IntegerField(default=0, null=True)),
                ("total_orders", models.IntegerField(default=0, null=True)),
                ("total_reviews", models.IntegerField(default=0, null=True)),
                ("total_ratings", models.IntegerField(default=0, null=True)),
                ("total_customers", models.IntegerField(default=0, null=True)),
                ("total_products_sold", models.IntegerField(default=0, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="seller_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.seller"
            ),
        ),
    ]
