# Generated by Django 5.1.7 on 2025-07-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_rename_id_cart_cart_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="discount_amount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="discount_percentage",
        ),
    ]
