# Generated by Django 5.1.7 on 2025-06-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_seller_product_seller_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="seller_id",
            field=models.CharField(
                editable=False,
                max_length=8,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                editable=False,
                max_length=5,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
