# Generated by Django 5.1.7 on 2025-07-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_remove_orderitem_discount_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
