# Generated by Django 5.1.7 on 2025-06-19 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_seller_seller_id_alter_user_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seller",
            old_name="total_customers",
            new_name="total_followers",
        ),
    ]
