# Generated by Django 5.1.7 on 2025-06-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_rename_total_customers_seller_total_followers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seller",
            name="total_ratings",
        ),
        migrations.AddField(
            model_name="seller",
            name="average_rating",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=3, null=True
            ),
        ),
    ]
