# Generated by Django 5.1.7 on 2025-06-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_remove_seller_total_ratings_seller_average_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="business_email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
