# Generated by Django 5.1.7 on 2025-06-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_seller_business_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.CharField(
                editable=False,
                max_length=8,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
