# Generated by Django 5.1.7 on 2025-06-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_alter_subcategory_sub_category_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subcategory",
            name="sub_category_name",
        ),
    ]
