# Generated by Django 5.1.7 on 2025-06-19 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_delete_subcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "sub_category_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("sub_category_description", models.CharField(max_length=255)),
                (
                    "sub_category_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="sub_category_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.category",
                    ),
                ),
            ],
        ),
    ]
