# Generated by Django 5.1.7 on 2025-06-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="sub_category_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
