# Generated by Django 5.1.7 on 2025-06-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_subcategory_sub_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="sub_category_id",
            field=models.CharField(
                editable=False,
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
