# Generated by Django 5.1.7 on 2025-06-20 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_alter_subcategory_sub_category_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sub_category_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.subcategory",
            ),
        ),
    ]
