# Generated by Django 5.1.7 on 2025-06-20 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_product_sub_category_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="review_count",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "review_id",
                    models.CharField(
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("review_rating", models.IntegerField(default=0)),
                ("review_comment", models.CharField(max_length=255)),
                ("review_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.product",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "Reviews",
            },
        ),
    ]
