# Generated by Django 5.1.7 on 2025-06-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_product_review_count_reviews"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promo",
            fields=[
                (
                    "promo_id",
                    models.CharField(
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("promo_name", models.CharField(max_length=255)),
                ("promo_description", models.CharField(max_length=255)),
                ("promo_code", models.CharField(max_length=255)),
                ("promo_discount", models.IntegerField(default=0)),
                ("promo_start_date", models.DateTimeField(null=True)),
                ("promo_end_date", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "Promo",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="category_description",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
