# Generated by Django 5.1.7 on 2025-06-20 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_promo_category_category_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promo",
            name="discount_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="promo",
            name="discount_percentage",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="promo",
            name="discount_type",
            field=models.CharField(
                choices=[("PERCENTAGE", "Percentage"), ("FIXED", "Fixed")],
                default="FIXED",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="promo",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="promo",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="promo",
            name="product_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.product"
            ),
        ),
        migrations.AddField(
            model_name="promo",
            name="seller_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.seller"
            ),
        ),
        migrations.AddField(
            model_name="promo",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name="Promo_Details",
            fields=[
                (
                    "promo_details_id",
                    models.CharField(
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.product",
                    ),
                ),
                (
                    "promo_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.promo",
                    ),
                ),
            ],
            options={
                "db_table": "Promo_Details",
            },
        ),
    ]
