# Generated by Django 5.1.7 on 2025-06-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_promo_discount_amount_promo_discount_percentage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promo_details",
            name="product_id",
        ),
        migrations.AddField(
            model_name="promo_details",
            name="product_ids",
            field=models.ManyToManyField(blank=True, to="api.product"),
        ),
    ]
