# Generated by Django 5.1.7 on 2025-06-20 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_remove_promo_details_product_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promo",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="promo",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="promo",
            name="product_id",
        ),
        migrations.RemoveField(
            model_name="promo",
            name="promo_discount",
        ),
        migrations.RemoveField(
            model_name="promo",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="promo_details",
            name="product_ids",
        ),
        migrations.AddField(
            model_name="promo_details",
            name="product_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.product"
            ),
        ),
        migrations.AlterField(
            model_name="promo",
            name="promo_code",
            field=models.CharField(
                default="", editable=False, max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="promo",
            name="promo_description",
            field=models.CharField(default="", max_length=255),
        ),
    ]
