# Generated by Django 5.1.7 on 2025-06-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_remove_promo_end_date_remove_promo_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promo",
            name="promo_code",
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="promo",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
