# Generated by Django 5.1.7 on 2025-06-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_remove_promo_promo_code_product_weight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="has_promo",
            field=models.BooleanField(default=False),
        ),
    ]
