# Generated by Django 5.1.7 on 2025-06-23 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_product_has_promo"),
    ]

    operations = [
        migrations.AddField(
            model_name="promo",
            name="product_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.product"
            ),
        ),
        migrations.DeleteModel(
            name="Promo_Details",
        ),
    ]
