# Generated by Django 5.1.7 on 2025-06-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_promo_product_id_delete_promo_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promo",
            name="product_id",
        ),
        migrations.AddField(
            model_name="promo",
            name="product_ids",
            field=models.ManyToManyField(related_name="promos", to="api.product"),
        ),
    ]
