# Generated by Django 5.1.7 on 2025-06-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_remove_promo_product_id_promo_product_ids"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promo",
            old_name="product_ids",
            new_name="product_id",
        ),
        migrations.AlterField(
            model_name="seller",
            name="business_email",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
