# Generated by Django 5.1.7 on 2025-06-23 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_rename_product_ids_promo_product_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promo",
            name="seller_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.seller"
            ),
        ),
    ]
