# Generated by Django 5.1.7 on 2025-06-23 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_alter_promo_seller_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("ROTTEN", "Rotten"),
                    ("SLIGHTLY_WILTED", "Slightly Wilted"),
                    ("FRESH", "Fresh"),
                ],
                default="FRESH",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="promo",
            name="seller_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.seller",
            ),
        ),
    ]
