# Generated by Django 5.1.7 on 2025-06-24 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_alter_product_product_status_cart_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="user_id",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
        ),
    ]
