# Generated by Django 5.1.7 on 2025-06-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_cart_total_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
