# Generated by Django 5.1.7 on 2025-06-25 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_alter_category_options_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table=None,
        ),
    ]
