# Generated by Django 5.1.7 on 2025-06-25 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_alter_category_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="total_price",
            new_name="total_item_price",
        ),
    ]
