# Generated by Django 5.1.7 on 2025-06-30 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category_id",
        ),
    ]
