# Generated by Django 5.1.7 on 2025-07-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_remove_product_category_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="cart_id",
            field=models.CharField(
                editable=False,
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                editable=False,
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order_item_id",
            field=models.CharField(
                editable=False,
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.CharField(
                editable=False,
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="promo",
            name="promo_id",
            field=models.CharField(
                editable=False,
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="review_id",
            field=models.CharField(
                editable=False,
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="seller_id",
            field=models.CharField(
                editable=False,
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                editable=False,
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
