# Generated by Django 5.1.7 on 2025-07-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_alter_user_options_remove_user_user_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$870000$8tC9ZfbtLiz4pun9NtWoVI$U09yvjqrxoIgK1bU4CPVD8qyVMA0T5EB8Ejnzibrluw=",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
