# Generated by Django 5.1.7 on 2025-07-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_alter_user_password_alter_user_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$870000$lj5GQfMzg6E9UzKYfHGxhs$NZMbKbsAySAMul65Nt4zKB+kpF6+ss00VlkvKn+lFCo=",
                max_length=128,
            ),
        ),
    ]
