# Generated by Django 5.1.7 on 2025-07-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$870000$XMpr7BgIq2Q8cjmC6QGlZ3$2OLprIVXJopda35N0XzIMmX33ADH99uLbPpbloupnMA=",
                max_length=128,
            ),
        ),
    ]
