# Generated by Django 5.1.7 on 2025-07-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_alter_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$870000$GXjRontg5hi37HOCPCFUSO$ePtyJL9YUIy8STZ3SfREytNH8eEBbS2RPHSaBiVEIGU=",
                max_length=128,
            ),
        ),
    ]
