# Generated by Django 5.1.7 on 2025-07-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_remove_user_is_admin_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
