# Generated by Django 5.1.7 on 2025-07-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_user_is_admin_alter_user_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
