# Generated by Django 5.1.7 on 2025-07-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0059_alter_user_password_alter_user_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
    ]
