# Generated by Django 5.1.7 on 2025-07-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0060_remove_user_is_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("seller", "Seller"),
                    ("customer", "Customer"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
