# Generated by Django 5.1.7 on 2025-07-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0061_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_sku",
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
