# Generated by Django 5.1.7 on 2025-07-07 05:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0062_alter_product_product_sku"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="offer_end_date",
        ),
        migrations.RemoveField(
            model_name="product",
            name="offer_start_date",
        ),
        migrations.AddField(
            model_name="seller",
            name="total_likes",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="promo",
            name="promo_end_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="promo",
            name="promo_start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
