# Generated by Django 5.1.7 on 2025-07-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0063_remove_product_offer_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="business_email",
            field=models.EmailField(editable=False, max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterModelTable(
            name="seller",
            table="Seller",
        ),
        migrations.AlterModelTable(
            name="user",
            table="Users",
        ),
    ]
