# Generated by Django 5.1.7 on 2025-07-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_alter_seller_business_email_alter_user_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
