# Generated by Django 5.1.7 on 2025-07-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_alter_user_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="average_rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="seller",
            name="business_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="seller",
            name="total_followers",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="seller",
            name="total_likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="seller",
            name="total_orders",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="seller",
            name="total_products",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="seller",
            name="total_products_sold",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="seller",
            name="total_reviews",
            field=models.IntegerField(default=0),
        ),
    ]
