# Generated by Django 5.1.7 on 2025-07-07 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0066_alter_seller_average_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promo",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="promo",
            name="discount_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="promo",
            name="discount_type",
            field=models.CharField(
                choices=[("percentage", "Percentage"), ("fixed", "Fixed Amount")],
                default="percentage",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="promo",
            name="promo_description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="promo",
            name="promo_end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="promo",
            name="promo_start_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="promo",
            name="seller_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.seller"
            ),
        ),
    ]
