# Generated by Django 5.1.7 on 2025-07-08 03:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0067_alter_promo_discount_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promo",
            name="discount_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="promo",
            name="discount_percentage",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="promo",
            name="discount_type",
            field=models.CharField(
                choices=[("PERCENTAGE", "Percentage"), ("FIXED", "Fixed")],
                default="FIXED",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="promo",
            name="promo_description",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="promo",
            name="promo_end_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="promo",
            name="promo_start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="promo",
            name="seller_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.seller",
            ),
        ),
    ]
