# Generated by Django 5.1.7 on 2025-07-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0068_alter_promo_discount_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promo",
            name="product_id",
        ),
    ]
