# Generated by Django 5.1.7 on 2025-07-08 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0069_remove_promo_product_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.product"
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.promo"
                    ),
                ),
            ],
            options={
                "db_table": "PromoProduct",
                "unique_together": {("promo", "product")},
            },
        ),
        migrations.AddField(
            model_name="promo",
            name="product_id",
            field=models.ManyToManyField(
                related_name="promos", through="api.PromoProduct", to="api.product"
            ),
        ),
    ]
